### ISSUE TITLE
Gamedata 질문생성 오류

### ISSUE THREAD

**Issue by hanaroo12** [OtterBK/Quizbot#2]
Gamedata에 첨부되어 있던 예제처럼 질문을 만들면 답을 입력하기도 전에 정답이 공개됩니다. 어떻게 해야하나요?

**Comment by OtterBK** [comment]
소스코드를 다시 올렸습니다.예제 파일로 실행한 결과 정상적으로 작동하는 것을 확인했습니다!만약 동일한 증상이 발생하면 디스코드 [제육보끔#1916] 으로 말씀해주세요!
또한 요청하신대로 예제를 자세하게 업데이트했습니다. 새로 올린 예제로 테스트해보세요.감사합니다.

**Comment by OtterBK** [comment]
소스코드를 다시 올렸습니다.
예제 파일로 실행한 결과 정상적으로 작동하는 것을 확인했습니다!
만약 동일한 증상이 발생하면 디스코드 [제육보끔#1916] 으로 말씀해주세요!

또한 이전에 보낸 메일에 요청하신대로 예제를 업데이트했습니다. 새로 올린 예제로 테스트해보세요.
감사합니다.

2021년 2월 19일 (금) 오후 5:24, hanaroo12 <notifications@github.com>님이 작성:
